"""Domain core: pure models, ports and rules. No frame/ML library, no I/O."""

from __future__ import annotations

from .config import (
    BudgetConfig,
    CVConfig,
    EnsembleConfig,
    FeatureSelectionConfig,
    FEConfig,
    HPOConfig,
    RunConfig,
    TrackerConfig,
)
from .context import RunContext
from .dataset import Dataset
from .exceptions import (
    ArtifactIntegrityError,
    AutoMLError,
    BudgetExhaustedError,
    ConfigError,
    FeatureSelectionError,
    FitFailedError,
    InputError,
    MissingDependencyError,
    NativeCategoricalONNXUnsupportedError,
    NotFittedError,
    PluginConflictError,
    SchemaValidationError,
    UnsupportedSchemeError,
)
from .logging import get_logger, log_stage
from .ports import (
    Budget,
    Calibrator,
    CalibratorFactory,
    CandidateCache,
    Capabilities,
    CVSplitter,
    Ensembler,
    EnsembleRecipe,
    Estimator,
    ExperimentTracker,
    FeatureRanker,
    FeatureSubsetSelector,
    Fold,
    GroupAwareSplitter,
    Metric,
    MetricNeeds,
    ModelFiles,
    ModelSerializer,
    ModelSpec,
    NoSignificanceTest,
    ParamSpec,
    ProbabilisticEstimator,
    ReportsSplitMeta,
    SearchSpace,
    SignificanceTest,
    SupportsEarlyStopping,
    SupportsFeatureImportance,
    SupportsNativeCategorical,
    SupportsNativeModel,
    SupportsShap,
    TimeOrderedSplitter,
    TuneOutcome,
    Tuner,
    parse_search_space,
    validate_fold,
)
from .schema import (
    CategoryTable,
    ColumnRole,
    DatetimeDeltaSpec,
    FeatureSchema,
    FrequencyEncodingSpec,
    IntersectionSpec,
    TargetEncodingSpec,
)
from .selection_policy import (
    BandResult,
    Candidate,
    SelectionPolicy,
    equivalence_band,
    rank,
    select_best,
)
from .task import Task, resolve_positive

__all__ = [
    # config / context / logging (M0)
    "RunConfig",
    "CVConfig",
    "BudgetConfig",
    "FEConfig",
    "FeatureSelectionConfig",
    "HPOConfig",
    "EnsembleConfig",
    "TrackerConfig",
    "RunContext",
    "get_logger",
    "log_stage",
    # exceptions (M0 + M1 + M8 integrity)
    "AutoMLError",
    "ConfigError",
    "UnsupportedSchemeError",
    "PluginConflictError",
    "MissingDependencyError",
    "SchemaValidationError",
    "NativeCategoricalONNXUnsupportedError",
    "ArtifactIntegrityError",
    "InputError",
    "NotFittedError",
    "BudgetExhaustedError",
    "FitFailedError",
    "FeatureSelectionError",
    # domain data core (M1a)
    "Task",
    "resolve_positive",
    "FeatureSchema",
    "ColumnRole",
    "CategoryTable",
    "Dataset",
    # feature-engineering specs (M6a)
    "DatetimeDeltaSpec",
    "TargetEncodingSpec",
    "FrequencyEncodingSpec",
    "IntersectionSpec",
    # ports (M1b)
    "Metric",
    "MetricNeeds",
    "Calibrator",
    "CalibratorFactory",
    "CVSplitter",
    "TimeOrderedSplitter",
    "GroupAwareSplitter",
    "ReportsSplitMeta",
    "Fold",
    "validate_fold",
    "Estimator",
    "ProbabilisticEstimator",
    "SupportsEarlyStopping",
    "SupportsFeatureImportance",
    "SupportsNativeCategorical",
    "SupportsNativeModel",
    "SupportsShap",
    "FeatureRanker",
    "FeatureSubsetSelector",
    "ModelSerializer",
    "ModelFiles",
    "ModelSpec",
    "Capabilities",
    "Budget",
    "CandidateCache",
    "SignificanceTest",
    "NoSignificanceTest",
    "ExperimentTracker",
    "Ensembler",
    "EnsembleRecipe",
    "Tuner",
    "TuneOutcome",
    "ParamSpec",
    "SearchSpace",
    "parse_search_space",
    # selection (M1b + M4a band)
    "SelectionPolicy",
    "Candidate",
    "select_best",
    "rank",
    "equivalence_band",
    "BandResult",
]
